services:
  - type: web
    name: mern-shopping
    runtime: node
    buildCommand: cd client && npm install && npm run build
    startCommand: cd server && node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000